export const examples = {
  "Cones": [
    { file: "2cone", description: "Basic 2D cone with 2 generators" },
    { file: "2cone_ineq", description: "2D cone defined by inequalities" },
    { file: "2cone_int", description: "2D cone with integer generators" },
    { file: "big", description: "Large cone with 30 generators" },
    { file: "bo5", description: "5D cone example" },
    { file: "cross2", description: "2D cross polytope cone" },
    { file: "gen_inhom_nonpointed", description: "Non-pointed inhomogeneous cone" },
    { file: "SubModularConeN4_hom", description: "Submodular cone in 4D" },
    { file: "huge", description: "Very large cone computation" },
    { file: "medium", description: "Medium-sized cone" },
    { file: "small", description: "Small cone example" },
    { file: "baby", description: "Minimal test example" },
    { file: "monoid", description: "Monoid generators" },
    { file: "monpoid", description: "Monoid variant" },
    { file: "monoid_auto", description: "Monoid with automorphisms" },
    { file: "monoid_weight", description: "Weighted monoid" },
    { file: "normface", description: "Normal fan face" },
    { file: "overflow", description: "Arithmetic overflow test" },
  ],

  "Polytopes": [
    { file: "cube_3", description: "3D unit cube" },
    { file: "cube_3_dual_fac", description: "Cube dual with factorization" },
    { file: "cyclicpolytope30-15", description: "Cyclic polytope (30 vertices, 15D)" },
    { file: "FortuneCookie", description: "Fortune cookie 9-vertex polytope" },
    { file: "cross-24", description: "24D cross polytope" },
    { file: "cut_poly_7", description: "Cut polytope in 14D" },
    { file: "pentagon", description: "2D pentagon" },
    { file: "polytope", description: "Basic polytope example" },
    { file: "polytope_deg1", description: "Polytope degree 1 elements" },
    { file: "SquareMinusVertex", description: "Square with vertex removed" },
    { file: "SquareMinusVertexPolyh", description: "Square-vertex as polyhedron" },
    { file: "SquareMinusVertexInhom", description: "Inhomogeneous square-vertex" },
    { file: "SquareMinusVertexStrict", description: "Strict inequalities variant" },
    { file: "Stanleydec", description: "Stanley decomposition" },
    { file: "max_polytope_cand", description: "Maximal polytope candidates" },
    { file: "halfspace2", description: "2D halfspace" },
    { file: "halfspace3inhom-input", description: "3D inhomogeneous halfspace" },
    { file: "square2", description: "Square polytope variant" },
  ],

  "Polyhedra (number fields)": [
    { file: "600cell", description: "600-cell (120 vertices)" },
    { file: "600cell-dual", description: "Dual of 600-cell" },
    { file: "B4", description: "Type B Coxeter polytope (17D)" },
    { file: "buckyball-v", description: "Buckyball polytope vertices" },
    { file: "dodecahedron-v", description: "Dodecahedron (20 vertices)" },
    { file: "grandantiprism", description: "Grand antiprism (100 vertices)" },
    { file: "great_rhombicuboctahedron-v", description: "Great rhombicuboctahedron" },
    { file: "icosahedron-h", description: "Icosahedron (H-representation)" },
    { file: "icosahedron-v", description: "Icosahedron (V-representation)" },
    { file: "icosahedron_prec", description: "Icosahedron precision test" },
    { file: "Kwak80", description: "Kwak's 80-vertex polytope" },
    { file: "small_rhombicuboctahedron-v", description: "Small rhombicuboctahedron" },
    { file: "truncateddodecahedron", description: "Truncated dodecahedron" },
    { file: "truncated_dodecahedron_dual", description: "Truncated dodecahedron dual" },
    { file: "truncated_dodecahefron_dual", description: "Truncated dodecahedron dual (alt)" },
  ],

  "Magic Squares": [
    { file: "3x3magic", description: "3x3 magic square" },
    { file: "3x3magicNGD", description: "3x3 magic, no grading denominator" },
    { file: "3x3magiceven", description: "Even 3x3 magic square sums" },
    { file: "3x3magiceven_lat", description: "Even magic square lattice" },
    { file: "3x3magiceven_sat", description: "Even magic square saturation" },
    { file: "4x4", description: "4x4 magic square" },
    { file: "5x5", description: "5x5 magic square" },
    { file: "5x5Gorenstein", description: "5x5 magic Gorenstein property" },
    { file: "5x5dual", description: "5x5 magic square dual cone" },
    { file: "6x6", description: "6x6 magic square" },
  ],

  "Voting / Social Choice": [
    { file: "Condorcet", description: "Condorcet voting polytope (24D)" },
    { file: "Condorcet.symm", description: "Symmetric Condorcet constraints" },
    { file: "Condorcet_one", description: "Condorcet with single candidate" },
    { file: "CondorcetExpansion", description: "Condorcet with expansion degree" },
    { file: "CondorcetFV", description: "Condorcet Fibonacci variant" },
    { file: "CondorcetInt", description: "Integer Condorcet constraints" },
    { file: "CondorcetN", description: "Normalized Condorcet voting" },
    { file: "CondorcetRange", description: "Range voting with bounds" },
    { file: "CondorcetSemi", description: "Semicontinuous Condorcet" },
    { file: "CondEffPlur", description: "Plurality voting effectiveness" },
    { file: "PluralityVsCutoff", description: "Plurality vs cutoff voting" },
    { file: "strictBorda", description: "Strict Borda count" },
    { file: "strictBorda_fixed_prec", description: "Strict Borda, fixed precision" },
  ],

  "Fusion Rings": [
    { file: "bracket_3_cand", description: "Fusion bracket (3 candidate)" },
    { file: "bracket_3_part", description: "Fusion bracket (3 partition)" },
    { file: "bracket_4", description: "Fusion bracket type (12 elements)" },
    { file: "bracket_4_comm", description: "Commutative fusion bracket" },
    { file: "bracket_4_comm_z2", description: "Fusion with Z2 structure" },
    { file: "bracket_4_single", description: "Single fusion bracket" },
    { file: "bracket_4_z2", description: "Z2 automorphism fusion" },
    { file: "C6_0", description: "Fusion type with 7 elements" },
    { file: "chosen_2", description: "Chosen fusion ring at index 2" },
    { file: "EH1", description: "Exceptional hypergeometric fusion" },
    { file: "find_mod_grad", description: "Modular gradings in fusion" },
    { file: "SWb2_hom", description: "Symmetric wall fusion type" },
    { file: "midi_ind", description: "Fusion induction (medium)" },
    { file: "mini_ind", description: "Fusion induction (small)" },
    { file: "mod_grad", description: "Modular grading example" },
  ],

  "Inequalities / Constraints": [
    { file: "InhomCong", description: "Inhomogeneous congruences" },
    { file: "InhomCongLat", description: "Inhomogeneous congruences lattice" },
    { file: "InhomCongSigns", description: "Congruences with sign restrictions" },
    { file: "InhomIneq", description: "Inhomogeneous inequalities (2D)" },
    { file: "InhomIneqIH", description: "Inhomogeneous with integer hull" },
    { file: "InhomIneqInc", description: "Inclusive inhomogeneous system" },
    { file: "InhomIneqSymb", description: "Symbolic inhomogeneous constraints" },
    { file: "InhomIneq_7", description: "Inhomogeneous 7D system" },
    { file: "InhomIneq_7_8", description: "Inhomogeneous 7D to 8D" },
    { file: "InhomIneq_gen", description: "General inhomogeneous inequalities" },
    { file: "InhomIneq_prec", description: "Precise inhomogeneous constraints" },
    { file: "IsEmpty", description: "Empty feasible region test" },
    { file: "IsNonEmpty", description: "Non-empty feasible region test" },
    { file: "dehomogenization", description: "Dehomogenization example" },
    { file: "NonCMDiv", description: "Non-Cohen-Macaulay divisor" },
    { file: "strict_sign", description: "Strict sign constraints" },
    { file: "no_open_facet", description: "No open facet example" },
    { file: "open_facet", description: "Open facet example" },
    { file: "subspace4", description: "Subspace in 4D" },
    { file: "poly_ineq", description: "Polynomial inequalities" },
    { file: "poly_equ", description: "Polynomial equations" },
    { file: "poly_hom_const", description: "Polynomial homogeneous constraints" },
    { file: "small_inhom_hbrc", description: "Small inhomogeneous HB rec cone" },
  ],

  "Lattices / Monoids": [
    { file: "A443", description: "Type A root lattice (40D)" },
    { file: "A443monoid", description: "Type A monoid structure" },
    { file: "A543", description: "Type A lattice (55D)" },
    { file: "A543monoid", description: "Type A monoid configuration" },
    { file: "A553", description: "Type A lattice variant" },
    { file: "A553_exp", description: "Type A with expansion" },
    { file: "A643", description: "Type A lattice configuration" },
    { file: "cone_latt_markov", description: "Markov cone and lattice" },
    { file: "cone_latt_markov_supp", description: "Markov lattice with support" },
    { file: "euclid", description: "Euclidean lattice" },
    { file: "IntClMonId", description: "Integral closure monoid ideal" },
    { file: "IntClMonIdSupp", description: "Monoid ideal with support" },
    { file: "MonIdeal", description: "Monoid ideal (Rees algebra)" },
    { file: "NumSemi", description: "Numerical semigroup" },
    { file: "ratlat_2", description: "Rational lattice (2D)" },
  ],

  "Toric / Algebraic": [
    { file: "toric_ideal", description: "Toric ideal" },
    { file: "toric_ideal_grb", description: "Toric ideal Groebner basis" },
    { file: "normal_toric_ideal", description: "Normal toric ideal" },
    { file: "non_toric", description: "Non-toric example" },
    { file: "rees", description: "Rees algebra" },
    { file: "lin_bin", description: "Linear binomial ideal" },
    { file: "representations", description: "Representation ring" },
    { file: "knapsack_11_60", description: "Knapsack problem (11 items)" },
  ],

  "Equations": [
    { file: "2equations", description: "Linear equations system (9D)" },
    { file: "2equations_default", description: "Equations with default options" },
    { file: "ChineseRemainder", description: "Chinese remainder equations" },
  ],

  "Projection": [
    { file: "small_proj", description: "Small projection example" },
    { file: "small_proj_inhom", description: "Inhomogeneous projection" },
    { file: "small_sh_proj", description: "Small support hyperplane proj" },
    { file: "small_sh_proj_inhom", description: "Inhomogeneous SH projection" },
  ],

  "Rational / Precision": [
    { file: "rational", description: "Rational coefficients" },
    { file: "rationalFL", description: "Rational face lattice" },
    { file: "rationalHSOP", description: "Rational HSOP" },
    { file: "rationalIH", description: "Rational integer hull" },
    { file: "rational_inhom", description: "Rational inhomogeneous" },
    { file: "tame", description: "Tame example" },
    { file: "tame_prec", description: "Tame with precision" },
  ],

  "Character Theory": [
    { file: "ChF_2_64", description: "Chevalley-Fourier character (2D)" },
    { file: "ChF_8_1024", description: "Chevalley-Fourier character (8D)" },
    { file: "ChF_16_1048576", description: "Chevalley-Fourier (16D)" },
    { file: "VdM_16_1048576", description: "Vandermonde matrix (16D)" },
  ],

  "Permutations / Graphs": [
    { file: "perm6_d4_nonsparse_indep_dual", description: "Permutation polytope 6D" },
    { file: "perm7_d2_dual", description: "Permutation polytope 7D dual" },
    { file: "semigraphoid5", description: "Semigraphoid axioms (5 vars)" },
    { file: "pet", description: "Petersen graph example" },
    { file: "pet_new", description: "Petersen graph variant" },
  ],

  "Other": [
    { file: "[1,1][0,1]", description: "Bracket notation polytope" },
    { file: "both_precomputed", description: "Precomputed basis + inequalities" },
    { file: "Jupiter", description: "Large mixed constraint system" },
    { file: "QConstSymb", description: "Quadratic symbolic constraint" },
    { file: "hickerson-16", description: "Hickerson example (16D)" },
    { file: "hickerson-18", description: "Hickerson example (18D)" },
    { file: "hickerson-18plus1", description: "Hickerson extended (18+1)" },
    { file: "hyper_crit", description: "Hypercritical example" },
    { file: "j462", description: "J462 example" },
    { file: "lo6", description: "Lo6 example" },
    { file: "pedro2", description: "Pedro2 example" },
    { file: "pythagoras", description: "Pythagorean constraints" },
    { file: "pythagoras_int", description: "Pythagorean (integer)" },
    { file: "pythagoras_rat", description: "Pythagorean (rational)" },
    { file: "rafa2416", description: "Rafa2416 example" },
  ],
};
